/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/hendersons_balance.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 102.66, 0]}>
        <group position={[40.26, 14.14, 0.46]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere5.geometry}
            material={nodes.Sphere5.material}
            position={[62.93, 13.93, 10.66]}
            rotation={[0, Math.PI / 9, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere4.geometry}
            material={nodes.Sphere4.material}
            position={[112.65, 13.93, 18.92]}
            rotation={[0, Math.PI / 9, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere2.geometry}
            material={nodes.Sphere2.material}
            position={[95.21, 13.93, -28.2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere1.geometry}
            material={nodes.Sphere1.material}
            position={[-190.26, 39.16, -0.46]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere.geometry}
            material={nodes.Sphere.material}
            position={[-40.26, -66.8, -0.46]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube.geometry}
            material={nodes.Cube.material}
            position={[-40.26, -14.14, -0.46]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/hendersons_balance.gltf')