/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/owl_table.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Subdivision_Surface.geometry}
        material={nodes.Subdivision_Surface.material}
        position={[0, 22.68, 0]}
        rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.leg.geometry}
          material={nodes.leg.material}
          position={[0.38, -91.61, -11.65]}
          rotation={[Math.PI / 2, 0, 0]}
          >
          <meshStandardMaterial color="#4D4D4D" />
         </mesh>   
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.leg.geometry}
          material={nodes.leg.material}
          position={[63.47, 42.99, -11.47]}
          rotation={[Math.PI / 2, 0, 0]}
          >
          <meshStandardMaterial color="#4D4D4D" />
         </mesh>   
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.leg.geometry}
          material={nodes.leg.material}
          position={[-62.92, 42.99, -11.82]}
          rotation={[Math.PI / 2, 0, 0]}
          >
          <meshStandardMaterial color="#4D4D4D" />
         </mesh>   
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.leg.geometry}
          material={nodes.leg.material}
          position={[0.38, 106.73, -11.65]}
          rotation={[Math.PI / 2, 0, 0]}
          >
          <meshStandardMaterial color="#4D4D4D" />
         </mesh>   
      </mesh>
    </group>
  )
}

useGLTF.preload('/owl_table.gltf')
