/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/snowspeeder.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -6.27, 11.34]}>
        <group position={[0.32, 3.13, -5.67]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.main.geometry}
            material={nodes.main.material}
            position={[-91.68, 3.51, -9.79]}
            material-color="#76CBCC"
            material-roughness="0.5" 
            material-metalness="0.8"            
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.rear_gun.geometry}
            material={nodes.rear_gun.material}
            position={[0.34, 58.2, 179.86]}
            material-color="#76CBCC"  
            material-roughness="0.5" 
            material-metalness="0.8"                       
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.side_cube.geometry}
            material={nodes.side_cube.material}
            position={[54.35, 43.06, -39.07]}
            rotation={[-0.02, 0.05, -0.7]}
            material-color="#3b3b3b"
            material-roughness="0.5" 
            material-metalness="0.8"             
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.canopy.geometry}
            material={nodes.canopy.material}
            position={[-0.55, 72.12, 24.1]}
            material-color="#76CBCC" 
            material-roughness="0.5" 
            material-metalness="0.8"                        
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.canopy_glass.geometry}
        material={nodes.canopy_glass.material}
        position={[-0.48, 70.16, 18.77]}
        material-color="#3b3b3b"  
        material-roughness="0.2"
        material-clearcoat="0.1"  
        material-metalness="0.3"             
      />
    </group>
  );
}

useGLTF.preload("/snowspeeder.glb");